#ifndef CREATURE_LIST_CPP
#define CREATURE_LIST_CPP

#include "Creature.h"

namespace Creature_List
{
    //                                     name,                   faction,      level,   upgrade level,   growth, 2_hex,  A,  D,  S, mD, MD, hp, speed,  morale,           luck,       fight, ai, { gold, m, s, c, g }, special abilities
    // Castle
    const Creature Pikeman (             "Pikeman",             Faction::Castle,     1, Creature::Upgrade_level::None,   14, false,  4,  5,  0,  1,  3,  10,  4, Morale::Good,    Luck::Neutral,  100,   80, {   60, 0, 0, 0, 0 }, "Immune to jousting.");
    const Creature Halberdier (          "Halberdier",          Faction::Castle,     1, Creature::Upgrade_level::First,  14, false,  6,  5,  0,  2,  3,  10,  5, Morale::Good,    Luck::Neutral,  115,  115, {   75, 0, 0, 0, 0 }, "Immune to jousting.");
    const Creature Archer (              "Archer",              Faction::Castle,     2, Creature::Upgrade_level::None,    9, false,  6,  3, 12,  2,  3,  10,  4, Morale::Good,    Luck::Neutral,  115,  126, {  100, 0, 0, 0, 0 }, "Ranged attack.");
    const Creature Marksman (            "Marksman",            Faction::Castle,     2, Creature::Upgrade_level::First,   9, false,  6,  3, 24,  2,  3,  10,  6, Morale::Good,    Luck::Neutral,  115,  184, {  150, 0, 0, 0, 0 }, "Ranged attack. Double attack.");
    const Creature Griffin (             "Griffin",             Faction::Castle,     3, Creature::Upgrade_level::None,    7, true,   8,  8,  0,  3,  6,  25,  6, Morale::Good,    Luck::Neutral,  324,  351, {  200, 0, 0, 0, 0 }, "Flying. Two retaliations.");
    const Creature Royal_Griffin (       "Royal Griffin",       Faction::Castle,     3, Creature::Upgrade_level::First,   7, true,   9,  9,  0,  3,  6,  25,  9, Morale::Good,    Luck::Neutral,  364,  448, {  240, 0, 0, 0, 0 }, "Flying. Unlimited retaliations.");
    const Creature Swordsman (           "Swordsman",           Faction::Castle,     4, Creature::Upgrade_level::None,    4, false, 10, 12,  0,  6,  9,  35,  5, Morale::Good,    Luck::Neutral,  445,  445, {  300, 0, 0, 0, 0 }, "");
    const Creature Crusader (            "Crusader",            Faction::Castle,     4, Creature::Upgrade_level::First,   4, false, 12, 12,  0,  7, 10,  35,  6, Morale::Good,    Luck::Neutral,  588,  588, {  400, 0, 0, 0, 0 }, "Double attack.");
    const Creature Monk (                "Monk",                Faction::Castle,     5, Creature::Upgrade_level::None,    3, false, 12,  7, 12, 10, 12,  30,  5, Morale::Good,    Luck::Neutral,  582,  485, {  400, 0, 0, 0, 0 }, "Ranged attack.");
    const Creature Zealot (              "Zealot",              Faction::Castle,     5, Creature::Upgrade_level::First,   3, false, 12, 10, 24, 10, 12,  30,  7, Morale::Good,    Luck::Neutral,  500,  750, {  450, 0, 0, 0, 0 }, "Ranged attack. No melee penalty.");
    const Creature Cavalier (            "Cavalier",            Faction::Castle,     6, Creature::Upgrade_level::None,    2, true,  15, 15,  0, 15, 25, 100,  7, Morale::Good,    Luck::Neutral, 1668, 1946, { 1000, 0, 0, 0, 0 }, "Jousting bonus.");
    const Creature Champion (            "Champion",            Faction::Castle,     6, Creature::Upgrade_level::First,   2, true,  16, 16,  0, 20, 25, 100,  9, Morale::Good,    Luck::Neutral, 1800, 2100, { 1200, 0, 0, 0, 0 }, "Jousting bonus.");
    const Creature Angel (               "Angel",               Faction::Castle,     7, Creature::Upgrade_level::None,    1, true,  20, 20,  0, 50, 50, 200, 12, Morale::Good,    Luck::Neutral, 3585, 5019, { 3000, 0, 0, 0, 1 }, "Flying. Hates Devils and Arch Devils. +1 morale to alias troops.");
    const Creature Archangel (           "Archangel",           Faction::Castle,     7, Creature::Upgrade_level::First,   1, true,  30, 30,  0, 50, 50, 250, 18, Morale::Good,    Luck::Neutral, 6033, 8776, { 5000, 0, 0, 0, 3 }, "Flying. Hates Devils and Arch Devils. +1 morale to alias troops. Can cast Ressurection once per battle.");
    
    // Rampart
    const Creature Centaur (             "Centaur",             Faction::Rampart,    1, Creature::Upgrade_level::None,   14, true,   5,  3,  0,  2,  3,   8,  6, Morale::Good,    Luck::Neutral,  100,  100, {   70, 0, 0, 0, 0 }, "");
    const Creature Centaur_Captain (     "Centaur Captain",     Faction::Rampart,    1, Creature::Upgrade_level::First,  14, true,   6,  3,  0,  2,  3,  10,  8, Morale::Good,    Luck::Neutral,  138,  138, {   90, 0, 0, 0, 0 }, "");
    const Creature Dwarf (               "Dwarf",               Faction::Rampart,    2, Creature::Upgrade_level::None,    8, false,  6,  7,  0,  2,  4,  20,  3, Morale::Good,    Luck::Neutral,  138,  138, {  120, 0, 0, 0, 0 }, "Magic resistance 20%.");
    const Creature Battle_Dwarf (        "Battle Dwarf",        Faction::Rampart,    2, Creature::Upgrade_level::First,   8, false,  7,  7,  0,  2,  4,  20,  5, Morale::Good,    Luck::Neutral,  209,  209, {  150, 0, 0, 0, 0 }, "Magic resistance 40%.");
    const Creature Wood_Elf (            "Wood Elf",            Faction::Rampart,    3, Creature::Upgrade_level::None,    7, false,  9,  5, 12,  3,  5,  15,  6, Morale::Good,    Luck::Neutral,  234,  234, {  200, 0, 0, 0, 0 }, "Ranged attack.");
    const Creature Grand_Elf (           "Grand Elf",           Faction::Rampart,    3, Creature::Upgrade_level::First,   7, false,  9,  5, 24,  3,  5,  15,  7, Morale::Good,    Luck::Neutral,  331,  331, {  225, 0, 0, 0, 0 }, "Ranged attack. Double attack.");
    const Creature Pegasus (             "Pegasus",             Faction::Rampart,    4, Creature::Upgrade_level::None,    5, true,   9,  8,  0,  5,  9,  30,  8, Morale::Good,    Luck::Neutral,  518,  518, {  250, 0, 0, 0, 0 }, "Magic damper.");
    const Creature Silver_Pegasus (      "Silver Pegasus",      Faction::Rampart,    4, Creature::Upgrade_level::First,   5, true,   9, 10,  0,  5,  9,  30, 12, Morale::Good,    Luck::Neutral,  532,  532, {  275, 0, 0, 0, 0 }, "Magic damper.");
    const Creature Dendroid_Guard (      "Dendroid Guard",      Faction::Rampart,    5, Creature::Upgrade_level::None,    3, false,  9, 12,  0, 10, 14,  55,  3, Morale::Good,    Luck::Neutral,  517,  517, {  350, 0, 0, 0, 0 }, "Binding attack.");
    const Creature Dendroid_Soldier (    "Dendroid Soldier",    Faction::Rampart,    5, Creature::Upgrade_level::First,   3, false,  9, 12,  0, 10, 14,  65,  4, Morale::Good,    Luck::Neutral,  765,  803, {  425, 0, 0, 0, 0 }, "Binding attack.");
    const Creature Unicorn (             "Unicorn",             Faction::Rampart,    6, Creature::Upgrade_level::None,    2, true,  15, 14,  0, 18, 22,  90,  7, Morale::Good,    Luck::Neutral, 1548, 1806, {  850, 0, 0, 0, 0 }, "20% chance to cast Blind per attack. Aura of magic resistance 20%.");
    const Creature War_Unicorn (         "War Unicorn",         Faction::Rampart,    6, Creature::Upgrade_level::First,   2, true,  15, 14,  0, 18, 22, 110,  9, Morale::Good,    Luck::Neutral, 2030, 2030, {  950, 0, 0, 0, 0 }, "20% chance to cast Blind per attack. Aura of magic resistance 20%.");
    const Creature Green_Dragon (        "Green Dragon",        Faction::Rampart,    7, Creature::Upgrade_level::None,    1, true,  18, 18,  0, 40, 50, 180, 10, Morale::Good,    Luck::Neutral, 3654, 4872, { 2400, 0, 0, 1, 0 }, "Breath attack. Immune to spells level 1-3.");
    const Creature Gold_Dragon (         "Gold Dragon",         Faction::Rampart,    7, Creature::Upgrade_level::First,   1, true,  27, 27,  0, 40, 50, 250, 16, Morale::Good,    Luck::Neutral, 6220, 8613, { 4000, 0, 0, 2, 0 }, "Breath attack. Immune to spells level 1-4.");

    // Tower
    const Creature Gremlin (             "Gremlin",             Faction::Tower,      1, Creature::Upgrade_level::None,   16, false,  3,  3,  0,  1,  2,   4,  4, Morale::Good,    Luck::Neutral,   55,   44, {   30, 0, 0, 0, 0 }, "");
    const Creature Master_Gremlin (      "Master Gremlin",      Faction::Tower,      1, Creature::Upgrade_level::First,  16, false,  4,  4,  8,  1,  2,   4,  5, Morale::Good,    Luck::Neutral,   55,   66, {   40, 0, 0, 0, 0 }, "Ranged attack.");
    const Creature Stone_Gargoyle (      "Stone Gargoyle",      Faction::Tower,      2, Creature::Upgrade_level::None,    9, false,  6,  6,  0,  2,  3,  16,  6, Morale::Good,    Luck::Neutral,  150,  165, {  130, 0, 0, 0, 0 }, "Non-living.");
    const Creature Obsidian_Gargoyle (   "Obsidian Gargoyle",   Faction::Tower,      2, Creature::Upgrade_level::First,   9, false,  7,  7,  0,  2,  3,  16,  9, Morale::Good,    Luck::Neutral,  155,  201, {  160, 0, 0, 0, 0 }, "Non-living.");
    const Creature Stone_Golem (         "Stone Golem",         Faction::Tower,      3, Creature::Upgrade_level::None,    6, false,  7, 10,  0,  4,  5,  30,  3, Morale::Neutral, Luck::Neutral,  339,  250, {  150, 0, 0, 0, 0 }, "Non-living. Spell damage reduction 50%.");
    const Creature Iron_Golem (          "Iron Golem",          Faction::Tower,      3, Creature::Upgrade_level::First,   6, false,  9, 10,  0,  4,  5,  35,  5, Morale::Neutral, Luck::Neutral,  412,  412, {  200, 0, 0, 0, 0 }, "Non-living. Spell damage reduction 75%.");
    const Creature Mage (                "Mage",                Faction::Tower,      4, Creature::Upgrade_level::None,    4, false, 11,  8, 24,  7,  5,  25,  5, Morale::Good,    Luck::Neutral,  418,  570, {  350, 0, 0, 0, 0 }, "Ranged attack. No melee penalty. No obstacle penalty. Hero's combat spells cost 2 less mana.");
    const Creature Arch_Mage (           "Arch Mage",           Faction::Tower,      4, Creature::Upgrade_level::First,   4, false, 12,  9, 24,  7,  9,  30,  7, Morale::Good,    Luck::Neutral,  467,  680, {  450, 0, 0, 0, 0 }, "Ranged attack. No melee penalty. No obstacle penalty. Hero's combat spells cost 2 less mana.");
    const Creature Genie (               "Genie",               Faction::Tower,      5, Creature::Upgrade_level::None,    3, false, 12, 12,  0, 13, 16,  40,  7, Morale::Good,    Luck::Neutral,  680,  884, {  550, 0, 0, 0, 0 }, "Hates Efreeti and Efreet Sultans.");
    const Creature Master_Genie (        "Master Genie",        Faction::Tower,      5, Creature::Upgrade_level::First,   3, false, 12, 12,  0, 13, 16,  40, 11, Morale::Good,    Luck::Neutral,  748,  942, {  600, 0, 0, 0, 0 }, "Hates Efreeti and Efreet Sultans. Spellcaster.");
    const Creature Naga (                "Naga",                Faction::Tower,      6, Creature::Upgrade_level::None,    2, true,  16, 13,  0, 20, 20, 110,  5, Morale::Good,    Luck::Neutral, 2016, 2016, { 1100, 0, 0, 0, 0 }, "No enemy retaliation.");
    const Creature Naga_Queen (          "Naga Queen",          Faction::Tower,      6, Creature::Upgrade_level::First,   2, true,  16, 13,  0, 30, 30, 110,  7, Morale::Good,    Luck::Neutral, 2840, 2840, { 1600, 0, 0, 0, 0 }, "No enemy retaliation.");
    const Creature Giant (               "Giant",               Faction::Tower,      7, Creature::Upgrade_level::None,    1, false, 19, 16,  0, 40, 60, 150,  7, Morale::Good,    Luck::Neutral, 3146, 3718, { 2000, 0, 0, 0, 1 }, "Immune to mind spells.");
    const Creature Titan (               "Titan",               Faction::Tower,      7, Creature::Upgrade_level::First,   1, false, 24, 24, 24, 40, 60, 300, 11, Morale::Good,    Luck::Neutral, 5000, 7500, { 5000, 0, 0, 0, 2 }, "Ranged attack. No melee penalty. Immune to mind spells. Hates Black Dragons.");

    // Inferno
    const Creature Imp (                 "Imp",                 Faction::Inferno,    1, Creature::Upgrade_level::None,   15, false,  2,  3,  0,  1,  2,   4,  5, Morale::Good,    Luck::Neutral,   50,   50, {   50, 0, 0, 0, 0 }, "");
    const Creature Familiar (            "Familiar",            Faction::Inferno,    1, Creature::Upgrade_level::First,  15, false,  4,  4,  0,  1,  2,   4,  7, Morale::Good,    Luck::Neutral,   60,   60, {   60, 0, 0, 0, 0 }, "Magic channel.");
    const Creature Gog (                 "Gog",                 Faction::Inferno,    2, Creature::Upgrade_level::None,    8, false,  6,  4, 12,  2,  4,  13,  4, Morale::Good,    Luck::Neutral,  145,  159, {  125, 0, 0, 0, 0 }, "Ranged attack.");
    const Creature Magog (               "Magog",               Faction::Inferno,    2, Creature::Upgrade_level::First,   8, false,  7,  4, 24,  2,  4,  13,  6, Morale::Good,    Luck::Neutral,  210,  240, {  175, 0, 0, 0, 0 }, "Ranged attack. Fireball attack.");
    const Creature Hell_Hound (          "Hell Hound",          Faction::Inferno,    3, Creature::Upgrade_level::None,    5, true,  10,  6,  0,  2,  7,  25,  7, Morale::Good,    Luck::Neutral,  275,  357, {  200, 0, 0, 0, 0 }, "");
    const Creature Cerberus (            "Cerberus",            Faction::Inferno,    3, Creature::Upgrade_level::First,   5, true,  10,  8,  0,  2,  7,  25,  8, Morale::Good,    Luck::Neutral,  308,  392, {  250, 0, 0, 0, 0 }, "3-headed attack. No enemy retaliation.");
    const Creature Demon (               "Demon",               Faction::Inferno,    4, Creature::Upgrade_level::None,    4, false, 10, 10,  0,  7,  9,  35,  5, Morale::Good,    Luck::Neutral,  445,  445, {  250, 0, 0, 0, 0 }, "");
    const Creature Horned_Demon (        "Horned Demon",        Faction::Inferno,    4, Creature::Upgrade_level::First,   4, false, 10, 10,  0,  7,  9,  40,  6, Morale::Good,    Luck::Neutral,  480,  480, {  270, 0, 0, 0, 0 }, "");
    const Creature Pit_Fiend (           "Pit Fiend",           Faction::Inferno,    5, Creature::Upgrade_level::None,    3, false, 13, 13,  0, 13, 17,  45,  6, Morale::Good,    Luck::Neutral,  765,  765, {  500, 0, 0, 0, 0 }, "");
    const Creature Pit_Lord (            "Pit Lord",            Faction::Inferno,    5, Creature::Upgrade_level::First,   3, false, 13, 13,  0, 13, 17,  45,  7, Morale::Good,    Luck::Neutral, 1071, 1224, {  700, 0, 0, 0, 0 }, "Summon Demons.");
    const Creature Efreet (              "Efreet",              Faction::Inferno,    6, Creature::Upgrade_level::None,    2, false, 16, 12,  0, 16, 24,  90,  9, Morale::Good,    Luck::Neutral, 1413, 1670, {  900, 0, 0, 0, 0 }, "Immune to fire spells (Magic Arrow included). Hates Genies and Master Genies.");
    const Creature Efreet_Sultan (       "Efreet Sultan",       Faction::Inferno,    6, Creature::Upgrade_level::First,   2, false, 16, 14,  0, 16, 24,  90, 13, Morale::Good,    Luck::Neutral, 1802, 2343, { 1100, 0, 0, 0, 0 }, "Immune to fire spells (Magic Arrow included). Hates Genies and Master Genies. Fire Shield.");
    const Creature Devil (               "Devil",               Faction::Inferno,    7, Creature::Upgrade_level::None,    1, false, 19, 21,  0, 30, 40, 160, 11, Morale::Good,    Luck::Neutral, 3759, 5101, { 2700, 1, 0, 0, 0 }, "-1 luck to enemy troops. No enemy retaliation. Hates Angels and Archangels.");
    const Creature Arch_Devil (          "Arch Devil",          Faction::Inferno,    7, Creature::Upgrade_level::First,   1, false, 26, 28,  0, 30, 40, 200, 17, Morale::Good,    Luck::Neutral, 5243, 7115, { 4500, 2, 0, 0, 0 }, "-2 luck to enemy troops. No enemy retaliation. Hates Angels and Archangels.");

    // Necropolis
    const Creature Skeleton (            "Skeleton",            Faction::Necropolis, 1, Creature::Upgrade_level::None,   12, false,  5,  4,  0,  1,  3,   6,  4, Morale::Neutral, Luck::Neutral,   75,   60, {   60, 0, 0, 0, 0 }, "Undead.");
    const Creature Skeleton_Warrior (    "Skeleton Warrior",    Faction::Necropolis, 1, Creature::Upgrade_level::First,  12, false,  6,  6,  0,  1,  3,   6,  5, Morale::Neutral, Luck::Neutral,   85,   85, {   70, 0, 0, 0, 0 }, "Undead.");
    const Creature Walking_Dead (        "Walking Dead",        Faction::Necropolis, 2, Creature::Upgrade_level::None,    8, false,  5,  5,  0,  2,  3,  15,  3, Morale::Neutral, Luck::Neutral,  140,   98, {  100, 0, 0, 0, 0 }, "Undead.");
    const Creature Zombie (              "Zombie",              Faction::Necropolis, 2, Creature::Upgrade_level::First,   8, false,  5,  5,  0,  2,  3,  20,  4, Morale::Neutral, Luck::Neutral,  160,  128, {  125, 0, 0, 0, 0 }, "Undead. 20% chance to cast Disease per attack.");
    const Creature Wight (               "Wight",               Faction::Necropolis, 3, Creature::Upgrade_level::None,    7, false,  7,  7,  0,  3,  5,  18,  5, Morale::Neutral, Luck::Neutral,  231,  252, {  200, 0, 0, 0, 0 }, "Undead. Regeneration.");
    const Creature Wraith (              "Wraith",              Faction::Necropolis, 3, Creature::Upgrade_level::First,   7, false,  7,  7,  0,  3,  5,  18,  7, Morale::Neutral, Luck::Neutral,  252,  315, {  230, 0, 0, 0, 0 }, "Undead. Regeneration. Mana drain.");
    const Creature Vampire (             "Vampire",             Faction::Necropolis, 4, Creature::Upgrade_level::None,    4, false, 10,  9,  0,  5,  8,  30,  6, Morale::Neutral, Luck::Neutral,  518,  555, {  360, 0, 0, 0, 0 }, "Undead. No enemy retaliation.");
    const Creature Vampire_Lord (        "Vampire Lord",        Faction::Necropolis, 4, Creature::Upgrade_level::First,   4, false, 10, 10,  0,  5,  8,  40,  9, Morale::Neutral, Luck::Neutral,  652,  783, {  500, 0, 0, 0, 0 }, "Undead. No enemy retaliation. Life drain.");
    const Creature Lich (                "Lich",                Faction::Necropolis, 5, Creature::Upgrade_level::None,    3, false, 13, 10, 12, 11, 13,  30,  6, Morale::Neutral, Luck::Neutral,  742,  848, {  550, 0, 0, 0, 0 }, "Undead. Ranged attack. Death cloud.");
    const Creature Power_Lich (          "Power Lich",          Faction::Necropolis, 5, Creature::Upgrade_level::First,   3, false, 13, 10, 24, 11, 15,  40,  7, Morale::Neutral, Luck::Neutral,  889, 1079, {  600, 0, 0, 0, 0 }, "Undead. Ranged attack. Death cloud.");
    const Creature Black_Knight (        "Black Knight",        Faction::Necropolis, 6, Creature::Upgrade_level::None,    2, true,  16, 16,  0, 15, 30, 120,  7, Morale::Neutral, Luck::Neutral, 1753, 2087, { 1200, 0, 0, 0, 0 }, "Undead. 25% chance to cast Curse per attack.");
    const Creature Dread_Knight (        "Dread Knight",        Faction::Necropolis, 6, Creature::Upgrade_level::First,   2, true,  18, 18,  0, 15, 30, 120,  9, Morale::Neutral, Luck::Neutral, 2029, 2382, { 1500, 0, 0, 0, 0 }, "Undead. 25% chance to cast Curse per attack. 20% chance to cast Death Blow per attack.");
    const Creature Bone_Dragon (         "Bone Dragon",         Faction::Necropolis, 7, Creature::Upgrade_level::None,    1, true,  17, 15,  0, 25, 50, 150,  9, Morale::Neutral, Luck::Neutral, 2420, 3388, { 1800, 0, 0, 0, 0 }, "Undead. -1 morale to enemy troops.");
    const Creature Ghost_Dragon (        "Ghost Dragon",        Faction::Necropolis, 7, Creature::Upgrade_level::First,   1, true,  19, 17,  0, 25, 50, 200, 14, Morale::Neutral, Luck::Neutral, 3228, 4696, { 3000, 1, 0, 0, 0 }, "Undead. -1 morale to enemy troops. 20% chance to cast Aging per attack.");
    
    // Dungeon
    const Creature Troglodyte (          "Troglodyte",          Faction::Dungeon,    1, Creature::Upgrade_level::None,   14, false,  4,  3,  0,  1,  3,   5,  4, Morale::Good,    Luck::Neutral,   73,   59, {   50, 0, 0, 0, 0 }, "Immune to Blind. Immune to Petrify.");
    const Creature Infernal_Troglodyte ( "Infernal Troglodyte", Faction::Dungeon,    1, Creature::Upgrade_level::First,  14, false,  5,  4,  0,  1,  3,   6,  5, Morale::Good,    Luck::Neutral,   84,   84, {   65, 0, 0, 0, 0 }, "Immune to Blind. Immune to Petrify.");
    const Creature Harpy (               "Harpy",               Faction::Dungeon,    2, Creature::Upgrade_level::None,    8, false,  6,  5,  0,  1,  4,  14,  6, Morale::Good,    Luck::Neutral,  140,  154, {  130, 0, 0, 0, 0 }, "Strike and return.");
    const Creature Harpy_Hag (           "Harpy Hag",           Faction::Dungeon,    2, Creature::Upgrade_level::First,   8, false,  6,  6,  0,  1,  4,  14,  9, Morale::Good,    Luck::Neutral,  196,  238, {  170, 0, 0, 0, 0 }, "Strike and return. No enemy retaliation.");
    const Creature Beholder (            "Beholder",            Faction::Dungeon,    3, Creature::Upgrade_level::None,    7, false,  9,  7, 12,  3,  5,  22,  5, Morale::Good,    Luck::Neutral,  240,  336, {  250, 0, 0, 0, 0 }, "Ranged attack. No melee penalty.");
    const Creature Evil_Eye (            "Evil Eye",            Faction::Dungeon,    3, Creature::Upgrade_level::First,   7, false, 10,  8, 24,  3,  5,  22,  7, Morale::Good,    Luck::Neutral,  245,  367, {  280, 0, 0, 0, 0 }, "Ranged attack. No melee penalty.");
    const Creature Medusa (              "Medusa",              Faction::Dungeon,    4, Creature::Upgrade_level::None,    4, true,   9,  9,  4,  6,  8,  25,  5, Morale::Good,    Luck::Neutral,  379,  517, {  300, 0, 0, 0, 0 }, "Ranged attack. No melee penalty. 20% chance to cast Petrify per melee attack.");
    const Creature Medusa_Queen (        "Medusa Queen",        Faction::Dungeon,    4, Creature::Upgrade_level::First,   4, true,  10, 10,  8,  6,  8,  30,  6, Morale::Good,    Luck::Neutral,  423,  577, {  330, 0, 0, 0, 0 }, "Ranged attack. No melee penalty. 20% chance to cast Petrify per melee attack.");
    const Creature Minotaur (            "Minotaur",            Faction::Dungeon,    5, Creature::Upgrade_level::None,    3, false, 14, 12,  0, 12, 20,  50,  6, Morale::Good,    Luck::Neutral,  835,  835, {  500, 0, 0, 0, 0 }, "Minimum morale is +1.");
    const Creature Minotaur_King (       "Minotaur King",       Faction::Dungeon,    5, Creature::Upgrade_level::First,   3, false, 15, 15,  0, 12, 20,  50,  8, Morale::Good,    Luck::Neutral,  890, 1068, {  575, 0, 0, 0, 0 }, "Minimum morale is +1.");
    const Creature Manticore (           "Manticore",           Faction::Dungeon,    6, Creature::Upgrade_level::None,    2, true,  15, 13,  0, 14, 20,  80,  7, Morale::Good,    Luck::Neutral, 1215, 1547, {  850, 0, 0, 0, 0 }, "");
    const Creature Scorpicore (          "Scorpicore",          Faction::Dungeon,    6, Creature::Upgrade_level::First,   2, true,  16, 14,  0, 14, 20,  80, 11, Morale::Good,    Luck::Neutral, 1248, 1589, { 1050, 0, 0, 0, 0 }, "20% chance to cast Paralyzing Venom per attack.");
    const Creature Red_Dragon (          "Red Dragon",          Faction::Dungeon,    7, Creature::Upgrade_level::None,    1, true,  19, 19,  0, 40, 50, 180, 11, Morale::Good,    Luck::Neutral, 3762, 4702, { 2500, 0, 1, 0, 0 }, "Breath attack. Immune to spells level 1-3.");
    const Creature Black_Dragon (        "Black Dragon",        Faction::Dungeon,    7, Creature::Upgrade_level::First,   1, true,  25, 25,  0, 40, 50, 300, 15, Morale::Good,    Luck::Neutral, 6783, 8721, { 4000, 0, 2, 0, 0 }, "Breath attack. Immune to all spells. Hates Titans.");

    // Stronghold
    const Creature Goblin (              "Goblin",              Faction::Stronghold, 1, Creature::Upgrade_level::None,   15, false,  4,  2,  0,  1,  2,   5,  5, Morale::Good,    Luck::Neutral,   60,   60, {   40, 0, 0, 0, 0 }, "");
    const Creature Hobgoblin (           "Hobgoblin",           Faction::Stronghold, 1, Creature::Upgrade_level::First,  15, false,  5,  3,  0,  1,  2,   5,  7, Morale::Good,    Luck::Neutral,   65,   78, {   50, 0, 0, 0, 0 }, "");
    const Creature Wolf_Rider (          "Wolf Rider",          Faction::Stronghold, 2, Creature::Upgrade_level::None,    9, true,   7,  5,  0,  2,  4,  10,  6, Morale::Good,    Luck::Neutral,  130,  130, {  100, 0, 0, 0, 0 }, "");
    const Creature Wolf_Raider (         "Wolf Raider",         Faction::Stronghold, 2, Creature::Upgrade_level::First,   9, true,   8,  5,  0,  3,  4,  10,  8, Morale::Good,    Luck::Neutral,  174,  203, {  140, 0, 0, 0, 0 }, "Double attack.");
    const Creature Orc (                 "Orc",                 Faction::Stronghold, 3, Creature::Upgrade_level::None,    7, false,  8,  4, 12,  2,  5,  15,  4, Morale::Good,    Luck::Neutral,  175,  192, {  150, 0, 0, 0, 0 }, "Ranged attack.");
    const Creature Orc_Chieftain (       "Orc Chieftain",       Faction::Stronghold, 3, Creature::Upgrade_level::First,   7, false,  8,  4, 24,  2,  5,  20,  5, Morale::Good,    Luck::Neutral,  200,  240, {  165, 0, 0, 0, 0 }, "Ranged attack.");
    const Creature Ogre (                "Ogre",                Faction::Stronghold, 4, Creature::Upgrade_level::None,    4, false, 13,  7,  4,  6, 12,  40,  4, Morale::Good,    Luck::Neutral,  520,  416, {  300, 0, 0, 0, 0 }, "");
    const Creature Ogre_Mage (           "Ogre Mage",           Faction::Stronghold, 4, Creature::Upgrade_level::First,   4, false, 13,  7,  8,  6, 12,  60,  5, Morale::Good,    Luck::Neutral,  672,  672, {  400, 0, 0, 0, 0 }, "Spellcaster (Bloodlust).");
    const Creature Roc (                 "Roc",                 Faction::Stronghold, 5, Creature::Upgrade_level::None,    3, true,  13, 11,  0, 11, 15,  60,  7, Morale::Good,    Luck::Neutral,  790, 1027, {  600, 0, 0, 0, 0 }, "");
    const Creature Thunderbird (         "Thunderbird",         Faction::Stronghold, 5, Creature::Upgrade_level::First,   3, true,  13, 11,  0, 11, 15,  60, 11, Morale::Good,    Luck::Neutral,  869, 1106, {  700, 0, 0, 0, 0 }, "20% chance to cast Lightning Strike per attack.");
    const Creature Cyclops (             "Cyclops",             Faction::Stronghold, 6, Creature::Upgrade_level::None,    2, false, 15, 12, 16, 16, 20,  70,  6, Morale::Good,    Luck::Neutral, 1055, 1266, {  750, 0, 0, 0, 0 }, "Ranged attack. Can attack siege walls.");
    const Creature Cyclops_King (        "Cyclops King",        Faction::Stronghold, 6, Creature::Upgrade_level::First,   2, false, 17, 13, 24, 16, 20,  70,  8, Morale::Good,    Luck::Neutral, 1110, 1443, { 1100, 0, 0, 0, 0 }, "Ranged attack. Can attack siege walls.");
    const Creature Behemoth (            "Behemoth",            Faction::Stronghold, 7, Creature::Upgrade_level::None,    1, true,  17, 17,  0, 30, 50, 160,  6, Morale::Good,    Luck::Neutral, 3162, 3162, { 1500, 0, 0, 0, 0 }, "Ignores 40% of enemy's defense skill.");
    const Creature Ancient_Behemoth (    "Ancient Behemoth",    Faction::Stronghold, 7, Creature::Upgrade_level::First,   1, true,  19, 19,  0, 30, 50, 300,  9, Morale::Good,    Luck::Neutral, 5397, 6168, { 3000, 0, 0, 1, 0 }, "Ignores 80% of enemy's defense skill.");

    // Fortress
    const Creature Gnoll (               "Gnoll",               Faction::Fortress,   1, Creature::Upgrade_level::None,   12, false,  3,  5,  0,  2,  3,   6,  4, Morale::Good,    Luck::Neutral,   70,   56, {   50, 0, 0, 0, 0 }, "");
    const Creature Gnoll_Marauder (      "Gnoll Marauder",      Faction::Fortress,   1, Creature::Upgrade_level::First,  12, false,  4,  6,  0,  2,  3,   6,  5, Morale::Good,    Luck::Neutral,   90,   90, {   70, 0, 0, 0, 0 }, "");
    const Creature Lizardman (           "Lizardman",           Faction::Fortress,   2, Creature::Upgrade_level::None,    9, false,  5,  6, 12,  2,  3,  14,  4, Morale::Good,    Luck::Neutral,  115,  126, {  110, 0, 0, 0, 0 }, "Ranged attack.");
    const Creature Lizard_Warrior (      "Lizard Warrior",      Faction::Fortress,   2, Creature::Upgrade_level::First,   9, false,  6,  8, 24,  2,  5,  15,  5, Morale::Good,    Luck::Neutral,  130,  156, {  140, 0, 0, 0, 0 }, "Ranged attack.");
    const Creature Serpent_Fly (         "Serpent Fly",         Faction::Fortress,   3, Creature::Upgrade_level::None,    8, false,  7,  9,  0,  2,  5,  20,  9, Morale::Good,    Luck::Neutral,  215,  268, {  220, 0, 0, 0, 0 }, "Casts Dispel to benefical spells per attack.");
    const Creature Dragon_Fly (          "Dragon Fly",          Faction::Fortress,   3, Creature::Upgrade_level::First,   8, false,  8, 10,  0,  2,  5,  20, 13, Morale::Good,    Luck::Neutral,  250,  312, {  240, 0, 0, 0, 0 }, "Casts Dispel to benefical spells per attack. Casts Advanced Weakness per attack.");
    const Creature Basilisk (            "Basilisk",            Faction::Fortress,   4, Creature::Upgrade_level::None,    4, true,  11, 11,  4,  6, 10,  35,  5, Morale::Good,    Luck::Neutral,  506,  552, {  325, 0, 0, 0, 0 }, "20% chance to cast Petrify per attack.");
    const Creature Greater_Basilisk (    "Greater Basilisk",    Faction::Fortress,   4, Creature::Upgrade_level::First,   4, true,  12, 12,  8,  6, 10,  40,  7, Morale::Good,    Luck::Neutral,  561,  714, {  400, 0, 0, 0, 0 }, "20% chance to cast Petrify per attack.");
    const Creature Gorgon (              "Gorgon",              Faction::Fortress,   5, Creature::Upgrade_level::None,    3, true,  10, 14,  0, 12, 16,  70,  5, Morale::Good,    Luck::Neutral,  890,  890, {  525, 0, 0, 0, 0 }, "");
    const Creature Mighty_Gorgon (       "Mighty Gorgon",       Faction::Fortress,   5, Creature::Upgrade_level::First,   3, true,  11, 16,  0, 12, 16,  70,  6, Morale::Good,    Luck::Neutral, 1028, 1028, {  600, 0, 0, 0, 0 }, "10% chance to cast Death Stare per melee attack.");
    const Creature Wyvern (              "Wyvern",              Faction::Fortress,   6, Creature::Upgrade_level::None,    2, true,  14, 14,  0, 14, 18,  70,  7, Morale::Good,    Luck::Neutral, 1050, 1350, {  800, 0, 0, 0, 0 }, "");
    const Creature Wyvern_Monarch (      "Wyvern Monarch",      Faction::Fortress,   6, Creature::Upgrade_level::First,   2, true,  14, 14,  0, 18, 22,  70, 11, Morale::Good,    Luck::Neutral, 1518, 1518, { 1100, 0, 0, 0, 0 }, "30% chance to cast Poison per attack.");
    const Creature Hydra (               "Hydra",               Faction::Fortress,   7, Creature::Upgrade_level::None,    1, true,  16, 18,  0, 25, 45, 175,  5, Morale::Good,    Luck::Neutral, 4120, 4120, { 2200, 0, 0, 0, 0 }, "Attack all adjacent enemies. No enemy retaliation.");
    const Creature Chaos_Hydra (         "Chaos Hydra",         Faction::Fortress,   7, Creature::Upgrade_level::First,   1, true,  18, 20,  0, 25, 45, 250,  7, Morale::Good,    Luck::Neutral, 5272, 5931, { 3500, 0, 1, 0, 0 }, "Attack all adjacent enemies. No enemy retaliation.");

    // Conflux
    const Creature Pixie (               "Pixie",               Faction::Conflux,    1, Creature::Upgrade_level::None,   20, false,  2,  2,  0,  1,  2,   3,  7, Morale::Good,    Luck::Neutral,   40,   55, {   25, 0, 0, 0, 0 }, "");
    const Creature Sprite (              "Sprite",              Faction::Conflux,    1, Creature::Upgrade_level::First,  20, false,  2,  2,  0,  1,  3,   3,  9, Morale::Good,    Luck::Neutral,   70,   95, {   30, 0, 0, 0, 0 }, "No enemy retaliation.");
    const Creature Air_Elemental (       "Air Elemental",       Faction::Conflux,    2, Creature::Upgrade_level::None,    6, false,  9,  9,  0,  2,  8,  25,  7, Morale::Good,    Luck::Neutral,  324,  356, {  250, 0, 0, 0, 0 }, "Non-living. Immune to Meteor Shower. Vulnerable to Lightning Bolt, Chain Lightning and Armageddon.");
    const Creature Storm_Elemental (     "Storm Elemental",     Faction::Conflux,    2, Creature::Upgrade_level::First,   6, false,  9,  9, 24,  2,  8,  25,  8, Morale::Good,    Luck::Neutral,  324,  486, {  275, 0, 0, 0, 0 }, "Non-living. Ranged attack. Immune to Meteor Shower. Vulnerable to Lightning Bolt, Chain Lightning and Armageddon. Spellcaster (Protection from Air).");
    const Creature Water_Elemental (     "Water Elemental",     Faction::Conflux,    3, Creature::Upgrade_level::None,    6, true,   8, 10,  0,  3,  7,  30,  5, Morale::Good,    Luck::Neutral,  315,  315, {  300, 0, 0, 0, 0 }, "Non-living. Immune to Ice Bolt and Frost Ring. Vulnerable to Armageddon, Fireball, Inferno.");
    const Creature Ice_Elemental (       "Ice Elemental",       Faction::Conflux,    3, Creature::Upgrade_level::First,   6, true,   8, 10, 24,  3,  7,  30,  6, Morale::Good,    Luck::Neutral,  315,  380, {  375, 0, 0, 0, 0 }, "Non-living. Ranged attack. Immune to Ice Bolt and Frost Ring. Vulnerable to Armageddon, Fireball, Inferno. Spellcaster (Protection from Water).");
    const Creature Fire_Elemental (      "Fire Elemental",      Faction::Conflux,    4, Creature::Upgrade_level::None,    5, false, 10,  8,  0,  4,  6,  35,  6, Morale::Good,    Luck::Neutral,  345,  345, {  350, 0, 0, 0, 0 }, "Non-living. Immune to fire spells (Magic Arrow included). Vulnerable to Ice Bolt and Frost Ring.");
    const Creature Energy_Elemental (    "Energy Elemental",    Faction::Conflux,    4, Creature::Upgrade_level::First,   5, false, 12,  8,  0,  4,  6,  35,  8, Morale::Good,    Luck::Neutral,  360,  470, {  400, 0, 0, 0, 0 }, "Non-living. Immune to fire spells (Magic Arrow included). Vulnerable to Ice Bolt and Frost Ring. Spellcaster (Protection from Fire).");
    const Creature Earth_Elemental (     "Earth Elemental",     Faction::Conflux,    5, Creature::Upgrade_level::None,    4, false, 10, 10,  0,  4,  8,  40,  4, Morale::Good,    Luck::Neutral,  415,  330, {  400, 0, 0, 0, 0 }, "Non-living. Immune to Lightning Bolt, Chain Lightning and Armageddon. Vulnerable to Meteor Shower.");
    const Creature Magma_Elemental (     "Magma Elemental",     Faction::Conflux,    5, Creature::Upgrade_level::First,   4, false, 11, 11,  0,  6, 10,  40,  6, Morale::Good,    Luck::Neutral,  490,  490, {  500, 0, 0, 0, 0 }, "Non-living. Immune to Lightning Bolt, Chain Lightning and Armageddon. Vulnerable to Meteor Shower. Spellcaster (Protection from Earth).");
    const Creature Psychic_Elemental (   "Psychic Elemental",   Faction::Conflux,    6, Creature::Upgrade_level::None,    2, false, 15, 13,  0, 10, 20,  75,  7, Morale::Good,    Luck::Neutral, 1431, 1669, {  750, 0, 0, 0, 0 }, "Non-living. No enemy retaliation. Attack all adjacent hexes. Immune to mind spells.");
    const Creature Magic_Elemental (     "Magic Elemental",     Faction::Conflux,    6, Creature::Upgrade_level::First,   2, false, 15, 13,  0, 15, 25,  80,  9, Morale::Good,    Luck::Neutral, 1724, 2012, {  800, 0, 0, 0, 0 }, "Non-living. No enemy retaliation. Attack all adjacent hexes. Immune to all spells.");
    const Creature Firebird (            "Firebird",            Faction::Conflux,    7, Creature::Upgrade_level::None,    2, true,  18, 18,  0, 30, 40, 150, 15, Morale::Good,    Luck::Neutral, 3248, 4547, { 1500, 0, 0, 0, 0 }, "Breath attack. Immune to fire spells (Magic Arrow included).");
    const Creature Phoenix (             "Phoenix",             Faction::Conflux,    7, Creature::Upgrade_level::First,   2, true,  21, 18,  0, 30, 40, 200, 21, Morale::Good,    Luck::Neutral, 4929, 6721, { 2000, 1, 0, 0, 0 }, "Breath attack. Rebirth. Immune to fire spells (Magic Arrow included).");
  
    // Cove
    const Creature Nymph (               "Nymph",               Faction::Cove,       1, Creature::Upgrade_level::None,   16, false,  5,  2,  0,  1,  2,   4,  6, Morale::Good,    Luck::Neutral,   52,   57, {   35, 0, 0, 0, 0 }, "Teleporting. Immune to Ice Bolt and Frost Ring.");
    const Creature Oceanid (             "Oceanid",             Faction::Cove,       1, Creature::Upgrade_level::First,  16, false,  6,  2,  0,  1,  3,   4,  8, Morale::Good,    Luck::Neutral,   60,   75, {   45, 0, 0, 0, 0 }, "Teleporting. Immune to Ice Bolt and Frost Ring.");
    const Creature Crew_Mate (           "Crew Mate",           Faction::Cove,       2, Creature::Upgrade_level::None,    9, false,  7,  4,  0,  2,  4,  15,  5, Morale::Good,    Luck::Neutral,  155,  155, {  110, 0, 0, 0, 0 }, "");
    const Creature Seaman (              "Seaman",              Faction::Cove,       2, Creature::Upgrade_level::First,   9, false,  8,  6,  0,  3,  4,  15,  6, Morale::Good,    Luck::Neutral,  174,  174, {  140, 0, 0, 0, 0 }, "");
    const Creature Pirate (              "Pirate",              Faction::Cove,       3, Creature::Upgrade_level::None,    7, false,  8,  6,  4,  3,  7,  15,  6, Morale::Good,    Luck::Neutral,  208,  312, {  225, 0, 0, 0, 0 }, "Ranged attack. No melee penalty.");
    const Creature Corsair (             "Corsair",             Faction::Cove,       3, Creature::Upgrade_level::First,   7, false, 10,  8,  4,  3,  7,  15,  7, Morale::Good,    Luck::Neutral,  311,  407, {  275, 0, 0, 0, 0 }, "Ranged attack. No melee penalty. No enemy retaliation.");
    const Creature Sea_Dog (             "Sea Dog",             Faction::Cove,       3, Creature::Upgrade_level::Second,  7, false, 12, 11, 12,  3,  7,  15,  8, Morale::Good,    Luck::Neutral,  376,  602, {  375, 0, 0, 0, 0 }, "Ranged attack. No melee penalty. No enemy retaliation. 10% chance to cast Accurate Shot per ranged attack.");
    const Creature Stormbird (           "Stormbird",           Faction::Cove,       4, Creature::Upgrade_level::None,    4, true,  10,  8,  0,  6,  9,  30,  9, Morale::Good,    Luck::Neutral,  386,  502, {  275, 0, 0, 0, 0 }, "");
    const Creature Ayssid (              "Ayssid",              Faction::Cove,       4, Creature::Upgrade_level::First,   4, true,  11,  8,  0,  6, 10,  30, 11, Morale::Good,    Luck::Neutral,  478,  645, {  325, 0, 0, 0, 0 }, "Ferocity.");
    const Creature Sea_Witch (           "Sea Witch",           Faction::Cove,       5, Creature::Upgrade_level::None,    3, false, 12,  7, 12, 10, 14,  35,  6, Morale::Good,    Luck::Neutral,  608,  790, {  515, 0, 0, 0, 0 }, "Ranged attack. Casts Weakness per attack. Casts Disrupting Ray on weakened enemies.");
    const Creature Sorceress (           "Sorceress",           Faction::Cove,       5, Creature::Upgrade_level::First,   3, false, 12,  9, 12, 10, 16,  35,  7, Morale::Good,    Luck::Neutral,  665,  852, {  565, 0, 0, 0, 0 }, "Ranged attack. Casts Advanced Weakness per attack. Casts Advanced Disrupting Ray on weakened enemies.");
    const Creature Nix (                 "Nix",                 Faction::Cove,       6, Creature::Upgrade_level::None,    2, false, 13, 16,  0, 18, 22,  80,  6, Morale::Good,    Luck::Neutral, 1415, 1415, { 1000, 0, 0, 0, 0 }, "Ignores 30% of enemy's attack skill.");
    const Creature Nix_Warrior (         "Nix Warrior",         Faction::Cove,       6, Creature::Upgrade_level::First,   2, false, 14, 17,  0, 18, 22,  90,  7, Morale::Good,    Luck::Neutral, 1763, 2116, { 1300, 0, 0, 0, 0 }, "Ignores 60% of enemy's attack skill.");
    const Creature Sea_Serpent (         "Sea Serpent",         Faction::Cove,       7, Creature::Upgrade_level::None,    1, true,  22, 16,  0, 30, 55, 180,  9, Morale::Good,    Luck::Neutral, 3162, 3953, { 2200, 0, 1, 0, 0 }, "30% chance to cast Poison per attack.");
    const Creature Haspid (              "Haspid",              Faction::Cove,       7, Creature::Upgrade_level::First,   1, true,  29, 20,  0, 30, 55, 300, 12, Morale::Good,    Luck::Neutral, 5554, 7220, { 4000, 0, 2, 0, 0 }, "30% chance to cast Poison per attack. Revenge.");

    // Neutral
    const Creature Peasant (             "Peasant",             Faction::Neutral,    1, Creature::Upgrade_level::None,   25, false,  1,  1,  0,  1,  1,   1,  3, Morale::Good,    Luck::Neutral,   15,   15, {   10, 0, 0, 0, 0 }, "");
    const Creature Halfling (            "Halfling",            Faction::Neutral,    1, Creature::Upgrade_level::None,   15, false,  4,  2, 24,  1,  3,   4,  5, Morale::Good,    Luck::Good,      60,   75, {   40, 0, 0, 0, 0 }, "Ranged attack. Minimum luck is +1.");
    const Creature Rogue (               "Rogue",               Faction::Neutral,    2, Creature::Upgrade_level::None,    8, false,  8,  3,  0,  2,  4,  10,  6, Morale::Good,    Luck::Neutral,  135,  135, {  100, 0, 0, 0, 0 }, "Spying.");
    const Creature Boar (                "Boar",                Faction::Neutral,    2, Creature::Upgrade_level::None,    8, true,   6,  5,  0,  2,  3,  15,  6, Morale::Good,    Luck::Neutral,  145,  145, {  150, 0, 0, 0, 0 }, "");
    const Creature Leprechaun (          "Leprechaun",          Faction::Neutral,    2, Creature::Upgrade_level::None,    9, false,  8,  5,  0,  3,  5,  15,  5, Morale::Good,    Luck::Good,     208,  208, {  100, 0, 0, 0, 0 }, "Doubles friendly unit Luck chance. Can cast Advanced Fortune 3 times per battle.");
    const Creature Nomad (               "Nomad",               Faction::Neutral,    3, Creature::Upgrade_level::None,    7, true,   9,  8,  0,  2,  6,  30,  7, Morale::Good,    Luck::Neutral,  415,  345, {  200, 0, 0, 0, 0 }, "Sandwalker.");
    const Creature Mummy (               "Mummy",               Faction::Neutral,    3, Creature::Upgrade_level::None,    7, false,  7,  7,  0,  3,  5,  30,  5, Morale::Neutral, Luck::Neutral,  270,  270, {  350, 0, 0, 0, 0 }, "Undead. 25% chance to cast Curse per attack.");
    const Creature Sharpshooter (        "Sharpshooter",        Faction::Neutral,    4, Creature::Upgrade_level::None,    4, false, 12, 10, 32,  8, 10,  15,  9, Morale::Good,    Luck::Neutral,  415,  585, {  400, 0, 0, 0, 0 }, "Ranged attack. No range penalty. No obstacle penalty.");
    const Creature Satyr (               "Satyr",               Faction::Neutral,    4, Creature::Upgrade_level::None,    4, false, 10, 11,  0,  6, 10,  35,  7, Morale::Good,    Luck::Neutral,  471,  518, {  350, 0, 0, 0, 0 }, "Can cast Advanced Mirth 3 times per battle.");
    const Creature Steel_Golem (         "Steel Golem",         Faction::Neutral,    4, Creature::Upgrade_level::None,    4, false, 10, 11,  0,  6,  8,  45,  6, Morale::Neutral, Luck::Neutral,  597,  597, {  400, 0, 0, 0, 0 }, "Non-living. Spell damage reduction 80%.");
    const Creature Troll (               "Troll",               Faction::Neutral,    5, Creature::Upgrade_level::None,    3, false, 14,  7,  0, 10, 15,  40,  7, Morale::Good,    Luck::Neutral, 1024, 1024, {  500, 0, 0, 0, 0 }, "Regeneration.");
    const Creature Gold_Golem (          "Gold Golem",          Faction::Neutral,    5, Creature::Upgrade_level::None,    3, false, 11, 12,  0,  8, 10,  50,  5, Morale::Neutral, Luck::Neutral,  600,  600, {  500, 0, 0, 0, 0 }, "Non-living. Spell damage reduction 85%.");
    const Creature Fangarm (             "Fangarm",             Faction::Neutral,    5, Creature::Upgrade_level::None,    3, false, 12, 12,  0,  8, 12,  50,  6, Morale::Good,    Luck::Neutral,  929,  929, {  600, 0, 0, 0, 0 }, "Immune to mind spells. Unlimited retaliations. Can cast Hypnotize per attack.");
    const Creature Diamond_Golem (       "Diamond Golem",       Faction::Neutral,    6, Creature::Upgrade_level::None,    2, false, 13, 12,  0, 10, 14,  60,  5, Morale::Neutral, Luck::Neutral,  775,  775, {  750, 0, 0, 0, 0 }, "Non-living. Spell damage reduction 95%.");  
    const Creature Enchanter (           "Enchanter",           Faction::Neutral,    6, Creature::Upgrade_level::None,    2, false, 17, 12, 32, 14, 14,  30,  9, Morale::Good,    Luck::Neutral,  805, 1210, {  750, 0, 0, 0, 0 }, "Ranged attack. No melee penalty. No obstacle penalty. Spellcaster.");  
    const Creature Faerie_Dragon (       "Faerie Dragon",       Faction::Neutral,    7, Creature::Upgrade_level::None,    1, true,  20, 20,  0, 20, 30, 500, 15, Morale::Good,    Luck::Neutral,16317,30501, {10000, 0, 0, 0, 8 }, "Spellcaster. Naturally has Magic Mirror.");  
    const Creature Rust_Dragon (         "Rust Dragon",         Faction::Neutral,    7, Creature::Upgrade_level::None,    1, true,  30, 30,  0, 50, 50, 750, 17, Morale::Good,    Luck::Neutral,24030,26433, {15000, 0,14, 0, 0 }, "Breath attack. Casts Weakness per attack. 20% chance to cast Acid Breath per attack.");  
    const Creature Crystal_Dragon (      "Crystal Dragon",      Faction::Neutral,    7, Creature::Upgrade_level::None,    1, true,  40, 40,  0, 60, 75, 800, 16, Morale::Good,    Luck::Neutral,30260,39338, {20000, 0, 0,10, 0 }, "Generates crystals. Magic resistance 20%.");  
    const Creature Azure_Dragon (        "Azure Dragon",        Faction::Neutral,    7, Creature::Upgrade_level::None,    1, true,  50, 50,  0, 70, 80,1000, 19, Morale::Good,    Luck::Neutral,56315,78845, {30000,20, 0, 0, 0 }, "Breath attack. 20% chance to cast Fear to adjacent enemies before they act. Immune to spells level 1-3. Immune to Fear.");  
}

#endif